"""empty message

Revision ID: 03fe8ac44b4c
Revises: 13d4bd30cda0
Create Date: 2026-06-26 16:51:50.560242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fe8ac44b4c'
down_revision = '13d4bd30cda0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commission', sa.Integer(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_affiliate', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('affiliate_id', sa.String(length=255), nullable=True))
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('google_id',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('affiliate_id')
        batch_op.drop_column('is_affiliate')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('commission')

    # ### end Alembic commands ###
