"""empty message

Revision ID: 2f93a68db24f
Revises: 5f935762df9c
Create Date: 2026-06-29 13:16:30.872977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f93a68db24f'
down_revision = '5f935762df9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_agent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('picked_up_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'agent', ['pickup_agent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refund', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('picked_up_at')
        batch_op.drop_column('pickup_agent_id')

    # ### end Alembic commands ###
