"""empty message

Revision ID: 5f935762df9c
Revises: 03fe8ac44b4c
Create Date: 2026-06-27 12:34:10.159780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f935762df9c'
down_revision = '03fe8ac44b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliate_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('affiliate_id')

    # ### end Alembic commands ###
