"""empty message

Revision ID: 78763834ed16
Revises: cdbcec72a432
Create Date: 2026-06-12 15:50:47.500077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78763834ed16'
down_revision = 'cdbcec72a432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shiprocket_order_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipment_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tracking_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('awb_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('awb_code')
        batch_op.drop_column('tracking_url')
        batch_op.drop_column('shipment_id')
        batch_op.drop_column('shiprocket_order_id')

    # ### end Alembic commands ###
