"""empty message

Revision ID: 8fd0f6d4bf97
Revises: 3c80d481bf4b
Create Date: 2026-07-01 11:48:58.837825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd0f6d4bf97'
down_revision = '3c80d481bf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_payout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'vendor_wallet_transaction', ['wallet_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_payout', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('wallet_transaction_id')

    # ### end Alembic commands ###
